language: node_js
node_js:
  - "6"
  - "6.1"
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"
before_script:
  - npm install -g gulp
  - npm install -g bithound
after_script:
  - npm run coveralls
  - bithound check git@github.com:ggarciao/gulp-standard-bundle.git